FROM ubuntu:16.04

RUN apt-get update && apt-get -y install \
	python3 \
	python3-dev \
	python3-setuptools \
	python3-pip \
	build-essential \
	libssl-dev \
	libffi-dev \
	python3-numpy \
	python3-scipy \
	python3-matplotlib \
	python3-pandas 

RUN pip3 install -U pip jupyter

# install all dependencies for OpenGrid
ADD requirements.txt /usr/local/opengrid/requirements.txt
RUN pip3 install -r /usr/local/opengrid/requirements.txt

# create volumes: one for the source code and work dir, one for the data
VOLUME /usr/local/opengrid
VOLUME /data

# add information for uploading a distribution to pypi.  No passwords!
ADD .pypirc /root/.pypirc

ENV PYTHONPATH=/usr/local/opengrid:$PYTHONPATH

WORKDIR /usr/local/opengrid

COPY charts-0.4.6-python3.tar.gz /usr/local/opengrid/charts-0.4.6-python3.tar.gz

RUN pip3 install -U /usr/local/opengrid/charts-0.4.6-python3.tar.gz

CMD ipython notebook --ip='*'

