FROM ubuntu:14.04

RUN apt-get update
RUN apt-get -y install python-numpy python-scipy python-matplotlib python-pandas python-pip
RUN pip install -U pip ipython notebook
ADD requirements.txt /usr/local/opengrid/requirements.txt
RUN pip install -f /usr/local/opengrid/requirements.txt

VOLUME /usr/local/opengrid

ENV PYTHONPATH=/usr/local/opengrid:$PYTHONPATH

WORKDIR /usr/local/opengrid/notebooks
CMD ipython notebook --ip='*'
